package com.example.reto;

import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.Fragment;
import androidx.navigation.Navigation;

import android.os.Bundle;
import android.widget.ImageButton;

/**
 * @author Jhon Doe
 */
public class MainActivity extends AppCompatActivity{

    Fragment content;

    /**
     * Autogenerated content
     * @param savedInstanceState Information
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);



        content = getSupportFragmentManager().findFragmentById(R.id.Content);

        ImageButton officeBtn = findViewById(R.id.offices_btn);
        officeBtn.setOnClickListener(view -> Navigation.findNavController(content.requireView()).navigate(R.id.offices));

        ImageButton partiesBtn = findViewById(R.id.parties_btn);
        partiesBtn.setOnClickListener(view -> Navigation.findNavController(content.requireView()).navigate(R.id.parties2));

        ImageButton servicesBtn = findViewById(R.id.services_btn);
        servicesBtn.setOnClickListener(view -> Navigation.findNavController(content.requireView()).navigate(R.id.services));
    }
}