package com.example.reto;

import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import androidx.navigation.Navigation;

import android.os.Bundle;
import android.view.View;
import android.view.Window;
import android.widget.FrameLayout;
import android.widget.ImageButton;

/**
 * @author Jhon Doe
 */
public class MainActivity extends AppCompatActivity{

    Fragment content;

    /**
     * Autogenerated content
     * @param savedInstanceState Information
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        content = getSupportFragmentManager().findFragmentById(R.id.Content);

        ImageButton officeBtn = findViewById(R.id.offices_btn);
        officeBtn.setOnClickListener(view -> changeContentTo(content.getView(), R.id.offices, "Offices"));

        ImageButton partiesBtn = findViewById(R.id.parties_btn);
        partiesBtn.setOnClickListener(view -> changeContentTo(content.getView(), R.id.parties2, "Parties"));

        ImageButton servicesBtn = findViewById(R.id.services_btn);
        servicesBtn.setOnClickListener(view -> changeContentTo(content.getView(), R.id.services, "Services"));
    }

    /**
     * Move into home fragments
     * @param view Button view
     * @param fragment Id of next fragment
     * @param title The title what will be in activity header
     */
    private void changeContentTo(View view, Integer fragment, String title){
        setTitle(title);
        Navigation.findNavController(view).navigate(fragment);
    }
}